function disableBubbleAndPreventDefault(ev){if(ev.preventDefault)ev.preventDefault();ev.cancelBubble=true;}
function setTouchEventOffsetPosition(ev,aa){ev=ev||event;if(ev.touches&&ev.touches.length){ev=ev.touches[0];}
else if(ev.changedTouches&&ev.changedTouches.length){ev=ev.changedTouches[0];}
var ba,offsetY;ba=ev.pageX-aa.x;offsetY=ev.pageY-aa.y;return{offsetX:ba,offsetY:offsetY};}
function crossLinesAndTipMgr(ca,da){if(typeof Tip!='function'){window.Tip=function(){};window.Tip.prototype={show:function(){},hide:function(){},update:function(){}};}
this.canvas=ca;this.options=da;}
crossLinesAndTipMgr.prototype._removeTipAndCrossLines=function(){var me=this;if(me.tip)me.tip.hide();if(me.clsMgr)me.clsMgr.removeCrossLines();};crossLinesAndTipMgr.prototype.updateOptions=function(ea){this.options=ea;};crossLinesAndTipMgr.prototype._onMouseOrTouchMove=function(ev){ev=ev||event;ev=getOffset(ev);var me=this;var fa=me.options;var ga=me.canvas;var ha=getPageCoord(ga);var ia=fa.triggerEventRanges;if(ev.offsetX<ia.x||ev.offsetX>ia.x+ia.width||ev.offsetY<ia.y||ev.offsetY>ia.y+ia.height){me._removeTipAndCrossLines();if(typeof(me.options.removeMAInfo)=="function")fa.removeMAInfo();if(typeof(HideTipYvalue)=="function")HideTipYvalue();return;}
var ja=fa.getCrossPoint(ev);var ka={crossPoint:ja,verticalRange:{y1:ia.y,y2:ia.y+ia.height},horizontalRange:{x1:ia.x,x2:ia.x+ia.width},color:fa.crossLineOptions.color,canvas:ga};var la=function(ma){ma=ma||event;ma=getOffset(ma);var na={offsetX:ma.offsetX+ia.x,offsetY:parseInt(me.clsMgr.getHLine().style.top)-ha.y};var oa=fa.getCrossPoint(na);me.clsMgr.updateCrossPoint(oa);if(me.tip){me.tip.update(oa,fa.tipOptions.getTipHtml(na),fa.triggerEventRanges,fa.tipOptions.position);}};var pa=function(qa){qa=qa||event;qa=getOffset(qa);var ra={offsetX:parseInt(me.clsMgr.getVLine().style.left)-ha.x,offsetY:qa.offsetY+ia.y};var sa=fa.getCrossPoint(ra);me.clsMgr.updateCrossPoint(sa);if(me.tip){me.tip.update(sa,fa.tipOptions.getTipHtml(ra),fa.triggerEventRanges,fa.tipOptions.position);}};if(!me.clsMgr){var ta=new crossLines(ka);ta.setMouseEvents(la,pa);me.clsMgr=ta;}
else{var ta=me.clsMgr;ta.updateOptions(ka);ta.setMouseEvents(la,pa);me.clsMgr=ta;}
me.clsMgr.drawCrossLines();if(fa.tipOptions){var ua=fa.tipOptions;if(!me.tip){var va=new Tip({position:{x:ua.position.x||false,y:ua.position.y||false},size:ua.size,opacity:ua.opacity||80,cssClass:ua.cssClass,style:ua.style,offsetToPoint:ua.offsetToPoint||30,relativePoint:{x:ja.x,y:ja.y},canvas:ga,canvasRange:fa.triggerEventRanges,innerHTML:ua.getTipHtml(ev)});me.tip=va;}
else{me.tip.update(ja,ua.getTipHtml(ev),fa.triggerEventRanges,ua.position);}
me.tip.show(ja,ua.getTipHtml(ev));}};crossLinesAndTipMgr.prototype._touchstart=function(ev){ev=ev||event;var wa=ev.srcElement||ev.target||ev.relatedTarget;this.touchstartTime=new Date();};crossLinesAndTipMgr.prototype._touchmove=function(ev){ev=ev||event;var xa=this.canvas;var ya=getPageCoord(xa);var za=ev.srcElement||ev.target||ev.relatedTarget;var Aa=setTouchEventOffsetPosition(ev,ya);this._onMouseOrTouchMove(Aa);};crossLinesAndTipMgr.prototype._touchend=function(ev){ev=ev||event;var Ba=ev.srcElement||ev.target||ev.relatedTarget;var Ca=this.canvas;var Da=setTouchEventOffsetPosition(ev,getPageCoord(Ca));this._removeTipAndCrossLines();var Ea=new Date();var ts=Ea.getTime()-this.touchstartTime.getTime();if(ts<200){if(typeof this.options.onClick=='function')this.options.onClick();}
if(typeof(this.options.removeMAInfo)=="function")this.options.removeMAInfo();if(typeof(HideTipYvalue)=="function")HideTipYvalue();};crossLinesAndTipMgr.prototype._mouseout=function(ev){var ev=ev||event;ev=getOffset(ev);var me=this;var Fa=me.options.triggerEventRanges;if(ev.offsetX<=Fa.x||ev.offsetX>=Fa.x+Fa.width||ev.offsetY<=Fa.y||ev.offsetY>=Fa.y+Fa.height){me._removeTipAndCrossLines();return;}
var Ga=ev.toElement||ev.relatedTarget||ev.target;if(Ga){if(Ga==me.canvas)return;if(Ga==me.clsMgr.getHLine()||Ga==me.clsMgr.getVLine())return;me._removeTipAndCrossLines();}};var isRemoveEvent;var handlerTouchStart;var handlerTouchMove;var handlerTouchEnd;var handlerMouseOut;var handlerMouseMove;var handlerMouseDown;var handlerMouseUp;crossLinesAndTipMgr.prototype.addCrossLinesAndTipEvents=function(){var Ha=this.canvas;var Ia=this.options;var Ja=getPageCoord(Ha);if(Ha.addCrossLinesAndTipEvents==true)return;var Ka=isTouchDevice();var me=this;if(Ka){if(isRemoveEvent){removeEvent(Ha,'touchstart',handlerTouchStart);removeEvent(Ha,'touchmove',handlerTouchMove);removeEvent(Ha,'touchend',handlerTouchEnd);isRemoveEvent=false;}
handlerTouchStart=function(ev){ev=ev||event;disableBubbleAndPreventDefault(ev);if(me.options.shouldDoControllerEvent(ev,'touchstart')){me.options.controllerEvents.onStart(ev);}
else{me._touchstart.call(me,ev);}};addEvent(Ha,'touchstart',handlerTouchStart);handlerTouchMove=function(ev){ev=ev||event;disableBubbleAndPreventDefault(ev);if(me.options.shouldDoControllerEvent(ev,'touchmove')){me.options.controllerEvents.onMove(ev);}
else{me._touchmove.call(me,ev);}};addEvent(Ha,'touchmove',handlerTouchMove);handlerTouchEnd=function(ev){ev=ev||event;disableBubbleAndPreventDefault(ev);if(me.options.shouldDoControllerEvent(ev,'touchend')){me.options.controllerEvents.onEnd(ev);}
me._touchend.call(me,ev);};addEvent(Ha,'touchend',handlerTouchEnd);}
else{if(isRemoveEvent){removeEvent(Ha,'mouseout',handlerMouseOut);removeEvent(Ha,'mousemove',handlerMouseMove);removeEvent(Ha,'mousedown',handlerMouseDown);removeEvent(Ha,'mouseup',handlerMouseUp);isRemoveEvent=false;}
handlerMouseOut=function(ev){ev=ev||event;if(me.options.shouldDoControllerEvent(ev)){me.options.controllerEvents.onEnd(ev);}
else{me._mouseout.call(me,ev);}};addEvent(Ha,'mouseout',handlerMouseOut);handlerMouseMove=function(ev){ev=ev||event;if("MouseState" in window&&MouseState!=0){me.options.controllerEvents.onMove(ev,MouseState);}
else{me._onMouseOrTouchMove.call(me,ev);}};addEvent(Ha,'mousemove',handlerMouseMove);addEvent(Ha,'mousedown',function(ev){ev=ev||window.event;if("MouseState" in window){MouseState=ev.which;me._removeTipAndCrossLines();if(typeof(HideTipYvalue)=="function")HideTipYvalue();}});addEvent(Ha,'mouseup',function(){if("MouseState" in window){MouseState=0;}});handlerMouseDown=function(ev){ev=ev||event;if(me.options.shouldDoControllerEvent(ev)){me.options.controllerEvents.onStart(ev);}};addEvent(Ha,'mousedown',handlerMouseDown);handlerMouseUp=function(ev){ev=ev||event;me.options.controllerEvents.onEnd(ev);};addEvent(Ha,'mouseup',handlerMouseUp);if(typeof Ia.onClick=='function'){addEvent(Ha,'click',Ia.onClick);}}};var MouseState=0;function addCrossLinesAndTipEvents(La,Ma){if(!La.crossLineAndTipMgrInstance){La.crossLineAndTipMgrInstance=new crossLinesAndTipMgr(La,Ma);La.crossLineAndTipMgrInstance.addCrossLinesAndTipEvents();}
else{La.crossLineAndTipMgrInstance.updateOptions(Ma);resetAllEvent(La,Ma);}}
function resetAllEvent(Na){var Oa=isTouchDevice();if(Oa){if(isRemoveEvent){removeEvent(Na,'touchstart',handlerTouchStart);removeEvent(Na,'touchmove',handlerTouchMove);removeEvent(Na,'touchend',handlerTouchEnd);isRemoveEvent=false;addEvent(Na,'touchstart',handlerTouchStart);addEvent(Na,'touchmove',handlerTouchMove);addEvent(Na,'touchend',handlerTouchEnd);}}
else{if(isRemoveEvent){removeEvent(Na,'mouseout',handlerMouseOut);removeEvent(Na,'mousemove',handlerMouseMove);removeEvent(Na,'mousedown',handlerMouseDown);removeEvent(Na,'mouseup',handlerMouseUp);isRemoveEvent=false;addEvent(Na,'mouseout',handlerMouseOut);addEvent(Na,'mousemove',handlerMouseMove);addEvent(Na,'mousedown',handlerMouseDown);addEvent(Na,'mouseup',handlerMouseUp);}}}